### ISSUE TITLE
Add favicon

### ISSUE THREAD

**Issue by s16h** [s16h/py-must-watch#41]
Perhaps the Python logo; maybe with a :movie_camera: (or something similar) on it.

**Comment by danjford** [comment]
How about this? A video camera with the python colours:

![image](https://cloud.githubusercontent.com/assets/7963046/10792638/61cdb946-7d85-11e5-802d-f48ca718d070.png)

**Comment by s16h** [comment]
Love it. Will you submit a PR?

**Comment by gromoleg** [comment]
:+1:

**Comment by techtonik** [comment]
Should it be closed?
