### ISSUE TITLE
Add "Brandon Rhodes - The Clean Architecture"

### ISSUE THREAD

**Issue by dduong42** [s16h/py-must-watch#42]
Brandon Rhodes - 2014:
https://www.youtube.com/watch?v=DJtef410XaM

It talks about isolating the logic from the routines instead of isolating the IOs.

**Comment by s16h** [comment]
Cool, thanks! I'll see the video and probably add it after; it sounds interesting.

**Comment by s16h** [comment]
I just finally watched this video and I found it very interesting. Could you create a pull request?
