### ISSUE TITLE
May I copy?

### ISSUE THREAD

**Issue by hellerve** [s16h/py-must-watch#45]
Hey,

Im compiling a little list of my own(to be found [here](https://github.com/hellerve/programming-talks)), and would like to incorporate a few of the resources you point to into it. Is that okay for you?

Cheers

**Comment by s16h** [comment]
That's fine with me. But, for the sake of reducing duplication an keeping your list up-to-date, wouldn't be easier to just put a link to here instead?

**Comment by hellerve** [comment]
You're right. I too hate fragmentation. Just incorporated a link to your repo.

Cheers
