### ISSUE TITLE
Add videos duration 

### ISSUE THREAD

**Issue by zalmanu** [s16h/py-must-watch#63]
Hi,

I think a good idea would be to add the video durations (similar to https://github.com/rosarior/django-must-watch/). I am willing to do it, but I would like to know if you are willing to merge the changes and if yes, in what form:
* add the durations only to the README file
* add them to the main page too.

Thanks!

**Comment by s16h** [comment]
Hey,

Thanks a lot for opening this issue. It sounds like a great idea actually. Let me have a think and get back to you regarding the format. I'm starting to think we should have a script that generates the `videos.json` file which can fill-in in stuff like duration automatically without us hard-coding it.

Thanks again!

**Comment by Thalmann** [comment]
I did sent a PR that solves this issue :-)

**Comment by Thalmann** [comment]
Until PR is accepted you can use the following: https://github.com/Thalmann/py-must-watch

**Comment by zalmanu** [comment]
:+1: @Thalmann

**Comment by gromoleg** [comment]
:+1:

On Wed, Dec 30, 2015 at 2:48 PM, Emanuel Danci <notifications@github.com>
wrote:

> [image: :+1:] @Thalmann <https://github.com/Thalmann>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/s16h/py-must-watch/issues/63#issuecomment-167991395>.
>



-- 
З повагою,
Олег Гром'як

With best regards,
Oleg Gromyak
