### ISSUE TITLE
Domain name expired?

### ISSUE THREAD

**Issue by ionelmc** [s16h/py-must-watch#76]
![image 3](https://cloud.githubusercontent.com/assets/129501/12139873/f4d80148-b46b-11e5-97e9-e14feb250ba1.png)

**Comment by s16h** [comment]
Ah thanks. I must've missed the expiry e-mail. It's renewed and should be back up soon.

**Comment by s16h** [comment]
It's back up. Thanks a lot!

**Comment by bittner** [comment]
http://pymust.watch now redirects to https://highlight.app/stajbakhsh/py-must-watch. Why?

This wasn't the case a few months or years ago, was it?
